# Generated by Django 6.0.2 on 2026-02-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab_tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150, unique=True)),
                ('sample_type', models.CharField(max_length=60, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='lab_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('result_summary', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='catalog.lab_tests')),
            ],
        ),
    ]
